export type Product = {
  id: string;
  title: string;
  brand: string;
  category: string;
  description: string;
  price: number;
  discount: number;
  finalPrice: number;
  rating: number;
  reviewsCount: number;
  stockQuantity: number;
  colors?: Record<string, string>[];
  sizes?: string[];
  tags?: string[];
  gallery: string[];
  shippingInfo?: string;
  warranty?: string;
  specifications?: Record<string, string>;
  soldCount?: number;
  returnPolicy?: string;
  createdAt: string;
};

export type Products = Product[];
const date = new Date();
const formattedDate = date.toLocaleDateString("en-CA");

export const products: Products = [
  {
    id: "1",
    title: "iPhone 14 Series",
    brand: "Apple",
    category: "Electronics",
    description:
      "Powerful and elegant, the iPhone 14 offers cutting-edge technology, stunning cameras, and an incredibly fast processor.",
    price: 1000,
    discount: 100,
    finalPrice: 900,
    rating: 4.8,
    reviewsCount: 5000,
    stockQuantity: 8,
    colors: [
      { color: "Midnight", hexCode: "#21212B" },
      { color: "Starlight", hexCode: "#F0EFE7" },
      { color: "Blue", hexCode: "#0000FF" },
      { color: "Red", hexCode: "#FF0000" },
    ],
    sizes: ["128GB"],
    tags: ["new-arrival", "top-rated", "Phones", "Electronics"],
    gallery: [
      "/products/iPhone 14 Series.png",
      "/products/test.png",
      "/products/iPhone 14 Series.png",
      "/products/test.png",
    ],
    shippingInfo: "Free shipping",
    warranty: "2 Year Warranty",
    specifications: {
      Display: "Super Retina XDR",
      Chip: "A15 Bionic",
    },
    soldCount: 25000,
    returnPolicy: "14-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "2",
    title: "DualSense Wireless Controller",
    brand: "Sony",
    category: "Gaming",
    description:
      "Experience deeper immersion with haptic feedback and dynamic adaptive triggers. It includes a built-in microphone and headset jack, all in an iconic, comfortable design.",
    price: 70,
    discount: 0,
    finalPrice: 70,
    rating: 4.9,
    reviewsCount: 9800,
    stockQuantity: 300,
    colors: [
      { color: "White", hexCode: "#FFFFFF" },
      { color: "Black", hexCode: "#000000" },
      { color: "Cosmic Red", hexCode: "#8B0000" },
      { color: "Midnight Black", hexCode: "#191970" },
    ],
    sizes: [],
    tags: ["gaming-accessory", "Controller", "PlayStation 5", "Gaming"],
    gallery: [
      "/products/DualSense Wireless Controller.png",
      "/products/test.png",
      "/products/DualSense Wireless Controller.png",
      "/products/test.png",
    ],
    shippingInfo: "Free shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Connectivity: "Wireless",
      Features: "Haptic Feedback, Adaptive Triggers",
      Battery: "Built-in rechargeable battery",
    },
    soldCount: 55000,
    returnPolicy: "30-day return policy",
    createdAt: formattedDate,
  },
  {
    id: "3",
    title: "Curology Product Set",
    brand: "Curology",
    category: "Health & Beauty",
    description:
      "A personalized skincare set designed to treat acne and improve skin texture, customized for your unique skin needs.",
    price: 60,
    discount: 0,
    finalPrice: 60,
    rating: 4.9,
    reviewsCount: 2100,
    stockQuantity: 200,
    colors: [],
    sizes: ["Full set"],
    tags: ["customized-skincare", "Health & Beauty"],
    gallery: [
      "/products/Curology Product Set.png",
      "/products/test.png",
      "/products/Curology Product Set.png",
      "/products/test.png",
    ],
    shippingInfo: "Free shipping",
    warranty: "N/A",
    specifications: {
      "Skin Type": "All",
      "Active Ingredients": "Custom",
    },
    soldCount: 15000,
    returnPolicy: "60-day money-back guarantee",
    createdAt: "2023-01-01",
  },
  {
    id: "4",
    title: "PlayStation 5",
    brand: "Sony",
    category: "Electronics",
    description:
      "Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with haptic feedback, and a new generation of incredible PlayStation games.",
    price: 500,
    discount: 0,
    finalPrice: 500,
    rating: 4.9,
    reviewsCount: 7500,
    stockQuantity: 30,
    colors: [{ color: "White", hexCode: "#FFFFFF" }],
    sizes: [],
    tags: ["gaming-console", "Gaming", "Electronics"],
    gallery: [
      "/products/PlayStation 5.png",
      "/products/test.png",
      "/products/PlayStation 5.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Storage: "825GB SSD",
      Graphics: "Ray Tracing",
    },
    soldCount: 45000,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "5",
    title: "Football Shoes",
    brand: "Nike",
    category: "Sports & Outdoor",
    description:
      "Designed for maximum speed and agility on the field, with a lightweight design and superior traction.",
    price: 90,
    discount: 15,
    finalPrice: 75,
    rating: 4.5,
    reviewsCount: 950,
    stockQuantity: 0,
    colors: [
      { color: "Black", hexCode: "#000000" },
      { color: "White", hexCode: "#FFFFFF" },
      { color: "Neon", hexCode: "#39FF14" },
    ],
    sizes: ["US 7", "US 8", "US 9", "US 10"],
    tags: ["soccer", "athletic", "Sports & Outdoor"],
    gallery: [
      "/products/Football Shoes.png",
      "/products/test.png",
      "/products/Football Shoes.png",
      "/products/test.png",
    ],
    shippingInfo: "Free delivery",
    warranty: "N/A",
    specifications: {
      Material: "Synthetic",
      Surface: "Firm Ground",
    },
    soldCount: 8200,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
  {
    id: "6",
    title: "Gucci Intense Oud Eau de Parfum",
    brand: "Gucci",
    category: "Health & Beauty",
    description:
      "A deep and luxurious fragrance with notes of oud, leather, and amber, creating a powerful and captivating scent.",
    price: 185,
    discount: 0,
    finalPrice: 185,
    rating: 4.8,
    reviewsCount: 850,
    stockQuantity: 60,
    colors: [],
    sizes: ["90ml"],
    tags: ["luxury", "oud", "Perfume", "Health & Beauty"],
    gallery: [
      "/products/Gucci Intense Oud Eau de Parfum.png",
      "/products/test.png",
      "/products/Gucci Intense Oud Eau de Parfum.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "N/A",
    specifications: {
      "Scent Type": "Oriental Woody",
      Volume: "90 ml",
    },
    soldCount: 4200,
    returnPolicy: "N/A (due to nature of product)",
    createdAt: "2023-01-01",
  },
  {
    id: "7",
    title: "Breed Dry Dog Food",
    brand: "Royal Canin",
    category: "Groceries & Pets",
    description:
      "Nutritionally complete dry dog food tailored to the specific needs of various dog breeds, promoting healthy digestion and a shiny coat.",
    price: 45,
    discount: 5,
    finalPrice: 40,
    rating: 4.7,
    reviewsCount: 600,
    stockQuantity: 180,
    colors: [],
    sizes: ["10kg", "20kg"],
    tags: ["pet-food", "dog-nutrition", "Groceries & Pets"],
    gallery: [
      "/products/Breed Dry Dog Food.png",
      "/products/test.png",
      "/products/Breed Dry Dog Food.png",
      "/products/test.png",
    ],
    shippingInfo: "Free delivery",
    warranty: "N/A",
    specifications: {
      "Age Range": "Adult",
      Ingredients: "Chicken meal, rice",
    },
    soldCount: 5500,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "8",
    title: "CANON EOS DSLR Camera",
    brand: "Canon",
    category: "Electronics",
    description:
      "Capture stunning high-resolution photos and videos with this professional-grade DSLR camera, perfect for both enthusiasts and pros.",
    price: 850,
    discount: 50,
    finalPrice: 800,
    rating: 4.8,
    reviewsCount: 1500,
    stockQuantity: 45,
    colors: [{ color: "Black", hexCode: "#000000" }],
    sizes: [],
    tags: ["photography", "Camera", "Electronics"],
    gallery: [
      "/products/CANON EOS DSLR Camera.png",
      "/products/test.png",
      "/products/CANON EOS DSLR Camera.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "2 Year Warranty",
    specifications: {
      Sensor: "24.1MP APS-C",
      Video: "1080p Full HD",
    },
    soldCount: 7800,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
  {
    id: "9",
    title: "ASUS FHD Gaming Laptop",
    brand: "ASUS",
    category: "Electronics",
    description:
      "A high-performance gaming laptop with a powerful processor, dedicated graphics card, and a crisp Full HD display for an immersive gaming experience.",
    price: 1200,
    discount: 150,
    finalPrice: 1050,
    rating: 4.7,
    reviewsCount: 2300,
    stockQuantity: 60,
    colors: [{ color: "Black", hexCode: "#000000" }],
    sizes: ["15.6 Inch"],
    tags: ["gaming-laptop", "Computers", "Electronics"],
    gallery: [
      "/products/ASUS FHD Gaming Laptop.png",
      "/products/test.png",
      "/products/ASUS FHD Gaming Laptop.png",
      "/products/test.png",
    ],
    shippingInfo: "Free shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Processor: "Intel Core i7",
      RAM: "16GB",
    },
    soldCount: 11000,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "10",
    title: "Kids Electric Car",
    brand: "Power Wheels",
    category: "Baby’s & Toys",
    description:
      "A safe and fun electric car for children, with realistic features like headlights, a horn, and a remote control for parental supervision.",
    price: 250,
    discount: 30,
    finalPrice: 220,
    rating: 4.6,
    reviewsCount: 750,
    stockQuantity: 90,
    colors: [
      { color: "Red", hexCode: "#FF0000" },
      { color: "Blue", hexCode: "#0000FF" },
      { color: "Pink", hexCode: "#FFC0CB" },
    ],
    sizes: [],
    tags: ["kid-friendly", "Baby’s & Toys"],
    gallery: [
      "/products/Kids Electric Car.png",
      "/products/test.png",
      "/products/Kids Electric Car.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "6 Month Warranty",
    specifications: {
      Battery: "12V",
      "Max Speed": "5 km/h",
    },
    soldCount: 6500,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
  {
    id: "11",
    title: "GP11 Shooter USB Gamepad",
    brand: "Logitech",
    category: "Gaming",
    description:
      "Ergonomic USB gamepad with responsive triggers and vibration feedback.",
    price: 120,
    discount: 40,
    finalPrice: 72,
    rating: 4.6,
    reviewsCount: 245,
    stockQuantity: 50,
    colors: [
      { color: "Black", hexCode: "#000000" },
      { color: "Red", hexCode: "#FF0000" },
    ],
    sizes: [],
    tags: ["best-seller", "discount", "Gaming"],
    gallery: [
      "/products/GP11 Shooter USB Gamepad.png",
      "/products/test.png",
      "/products/GP11 Shooter USB Gamepad.png",
      "/products/test.png",
    ],
    shippingInfo: "Free delivery in 2-4 days",
    warranty: "1 Year Warranty",
    specifications: {
      Connectivity: "USB 2.0",
      Compatibility: "PC, PlayStation",
    },
    soldCount: 3200,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "12",
    title: "RGB Liquid CPU Cooler",
    brand: "Corsair",
    category: "Electronics",
    description:
      "High-performance liquid CPU cooler with customizable RGB lighting, ensuring your processor stays cool under heavy load.",
    price: 150,
    discount: 20,
    finalPrice: 130,
    rating: 4.7,
    reviewsCount: 450,
    stockQuantity: 65,
    colors: [{ color: "Black", hexCode: "#000000" }],
    sizes: [],
    tags: ["pc-build", "rgb", "Computers", "Electronics"],
    gallery: [
      "/products/RGB Liquid CPU Cooler.png",
      "/products/test.png",
      "/products/RGB Liquid CPU Cooler.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "5 Year Warranty",
    specifications: {
      "Radiator Size": "240mm",
      "Socket Support": "LGA 1700, AM5",
    },
    soldCount: 4100,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
  {
    id: "13",
    title: "Gucci Duffle Bag",
    brand: "Gucci",
    category: "Men’s Fashion",
    description:
      "A stylish and luxurious duffle bag crafted from premium materials, perfect for travel or daily use.",
    price: 1800,
    discount: 0,
    finalPrice: 1800,
    rating: 4.9,
    reviewsCount: 350,
    stockQuantity: 15,
    colors: [
      { color: "Brown", hexCode: "#A52A2A" },
      { color: "Black", hexCode: "#000000" },
    ],
    sizes: ["One Size"],
    tags: ["luxury", "travel", "Men’s Fashion"],
    gallery: [
      "/products/Gucci Duffle Bag.png",
      "/products/test.png",
      "/products/Gucci Duffle Bag.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Material: "Leather",
      Dimensions: "50x30x25cm",
    },
    soldCount: 2500,
    returnPolicy: "N/A",
    createdAt: "2023-01-01",
  },
  {
    id: "14",
    title: "Small Bookshelf",
    brand: "IKEA",
    category: "Home & Lifestyle",
    description:
      "A compact and sturdy bookshelf with multiple shelves, ideal for organizing books and decor in small spaces.",
    price: 80,
    discount: 10,
    finalPrice: 70,
    rating: 4.5,
    reviewsCount: 550,
    stockQuantity: 100,
    colors: [
      { color: "White", hexCode: "#FFFFFF" },
      { color: "Oak", hexCode: "#A55233" },
    ],
    sizes: ["One Size"],
    tags: ["furniture", "storage", "Home & Lifestyle"],
    gallery: [
      "/products/Small Bookshelf.png",
      "/products/test.png",
      "/products/Small Bookshelf.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard delivery",
    warranty: "N/A",
    specifications: {
      Material: "Particleboard",
      Dimensions: "80x30x100cm",
    },
    soldCount: 4800,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
  {
    id: "15",
    title: "The North Coat",
    brand: "Columbia",
    category: "Men’s Fashion",
    description:
      "A waterproof and insulated coat designed to keep you warm and dry in cold weather, perfect for outdoor adventures.",
    price: 180,
    discount: 30,
    finalPrice: 150,
    rating: 4.6,
    reviewsCount: 800,
    stockQuantity: 70,
    colors: [
      { color: "Black", hexCode: "#000000" },
      { color: "Blue", hexCode: "#0000FF" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tags: ["winter-wear", "outdoor", "Men’s Fashion"],
    gallery: [
      "/products/The North Coat.png",
      "/products/test.png",
      "/products/The North Coat.png",
      "/products/test.png",
    ],
    shippingInfo: "Free shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Material: "Polyester",
      Insulation: "Synthetic",
    },
    soldCount: 7200,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "16",
    title: "S-Series Comfort Chair",
    brand: "Herman Miller",
    category: "Home & Lifestyle",
    description:
      "Ergonomic office chair with superior lumbar support and adjustable features, designed for long hours of comfortable seating.",
    price: 500,
    discount: 50,
    finalPrice: 450,
    rating: 4.8,
    reviewsCount: 950,
    stockQuantity: 40,
    colors: [
      { color: "Gray", hexCode: "#808080" },
      { color: "Black", hexCode: "#000000" },
    ],
    sizes: ["One Size"],
    tags: ["office-chair", "ergonomic", "Home & Lifestyle"],
    gallery: [
      "/products/S-Series Comfort Chair.png",
      "/products/test.png",
      "/products/S-Series Comfort Chair.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard delivery",
    warranty: "5 Year Warranty",
    specifications: {
      Adjustments: "Height, Tilt",
      Material: "Mesh",
    },
    soldCount: 5500,
    returnPolicy: "60-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "17",
    title: "AK-900 Wired Keyboard",
    brand: "Redragon",
    category: "Gaming",
    description:
      "A mechanical gaming keyboard with responsive keys and customizable RGB backlighting, built for durability and performance.",
    price: 60,
    discount: 10,
    finalPrice: 50,
    rating: 4.6,
    reviewsCount: 650,
    stockQuantity: 110,
    colors: [{ color: "Black", hexCode: "#000000" }],
    sizes: [],
    tags: ["mechanical-keyboard", "rgb", "Gaming"],
    gallery: [
      "/products/AK-900 Wired Keyboard.png",
      "/products/test.png",
      "/products/AK-900 Wired Keyboard.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "1 Year Warranty",
    specifications: {
      "Key Switches": "Blue Switches",
      Backlight: "RGB",
    },
    soldCount: 4900,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
  {
    id: "18",
    title: "HAVIT HV-G92 Gamepad",
    brand: "HAVIT",
    category: "Gaming",
    description:
      "A comfortable and reliable USB gamepad with dual vibration feedback, compatible with PC and various gaming platforms.",
    price: 25,
    discount: 5,
    finalPrice: 20,
    rating: 4.4,
    reviewsCount: 380,
    stockQuantity: 95,
    colors: [{ color: "Black", hexCode: "#000000" }],
    sizes: [],
    tags: ["gaming-accessory", "Gaming"],
    gallery: [
      "/products/HAVIT HV-G92 Gamepad.png",
      "/products/test.png",
      "/products/HAVIT HV-G92 Gamepad.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "6 Month Warranty",
    specifications: {
      Connectivity: "USB",
      Compatibility: "PC, Android",
    },
    soldCount: 3500,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "19",
    title: "Quilted Satin Jacket",
    brand: "Zara",
    category: "Woman’s Fashion",
    description:
      "A lightweight quilted satin jacket with a modern fit, perfect for layering in cool weather.",
    price: 95,
    discount: 15,
    finalPrice: 80,
    rating: 4.5,
    reviewsCount: 420,
    stockQuantity: 85,
    colors: [
      { color: "Black", hexCode: "#000000" },
      { color: "Green", hexCode: "#008000" },
      { color: "Burgundy", hexCode: "#800020" },
    ],
    sizes: ["S", "M", "L", "XL"],
    tags: ["fashion", "jacket", "Woman’s Fashion"],
    gallery: [
      "/products/Quilted Satin Jacket.png",
      "/products/test.png",
      "/products/Quilted Satin Jacket.png",
      "/products/test.png",
    ],
    shippingInfo: "Standard delivery",
    warranty: "N/A",
    specifications: {
      Material: "Satin",
      Style: "Casual",
    },
    soldCount: 6800,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "20",
    title: "IPS LCD Gaming Monitor",
    brand: "Dell",
    category: "Electronics",
    description:
      "A high-refresh-rate gaming monitor with a vibrant IPS panel, providing excellent color accuracy and fast response times for competitive gaming.",
    price: 280,
    discount: 30,
    finalPrice: 250,
    rating: 4.7,
    reviewsCount: 1200,
    stockQuantity: 55,
    colors: [{ color: "Black", hexCode: "#000000" }],
    sizes: ["27 Inch"],
    tags: ["gaming-monitor", "high-refresh", "Computers", "Electronics"],
    gallery: [
      "/products/IPS LCD Gaming Monitor.png",
      "/products/test.png",
      "/products/IPS LCD Gaming Monitor.png",
      "/products/test.png",
    ],
    shippingInfo: "Free shipping",
    warranty: "3 Year Warranty",
    specifications: {
      "Screen Size": "27 inch",
      "Refresh Rate": "144Hz",
    },
    soldCount: 9100,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "21",
    title: "Samsung Galaxy S23 Ultra",
    brand: "Samsung",
    category: "Electronics",
    description:
      "A feature-rich smartphone with a stunning camera, S Pen support, and powerful performance.",
    price: 1200,
    discount: 150,
    finalPrice: 1050,
    rating: 4.9,
    reviewsCount: 6500,
    stockQuantity: 200,
    colors: [
      { color: "Phantom Black", hexCode: "#181414" },
      { color: "Cream", hexCode: "#F5F5DC" },
      { color: "Green", hexCode: "#008000" },
      { color: "Lavender", hexCode: "#E6E6FA" },
    ],
    sizes: ["256GB", "512GB", "1TB"],
    tags: ["flagship", "best-camera", "Phones", "Electronics"],
    gallery: [
      "/products/Samsung Galaxy S23 Ultra.png",
      "/products/test.png",
      "/products/Samsung Galaxy S23 Ultra.png",
      "/products/test.png",
    ],
    shippingInfo: "Free express shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Display: "Dynamic AMOLED 2X",
      Chip: "Snapdragon 8 Gen 2",
    },
    soldCount: 30000,
    returnPolicy: "30-day return",
    createdAt: "2023-01-01",
  },
  {
    id: "22",
    title: "Amazon Echo (2nd Generation)",
    brand: "Amazon",
    category: "Electronics",
    description: "Smart speaker with Alexa.",
    price: 80,
    discount: 15,
    finalPrice: 65,
    rating: 4.5,
    reviewsCount: 1500,
    stockQuantity: 150,
    colors: [
      { color: "Charcoal Fabric", hexCode: "#2C313C" },
      { color: "Heather Gray Fabric", hexCode: "#A8A8A8" },
      { color: "Sandstone Fabric", hexCode: "#E6D7B9" },
    ],
    sizes: [],
    tags: ["Speakers", "smart-speaker", "Electronics"],
    gallery: [
      "/products/Amazon Echo (2nd Generation).png",
      "/products/test.png",
      "/products/Amazon Echo (2nd Generation).png",
      "/products/test.png",
    ],
    shippingInfo: "Standard shipping",
    warranty: "1 Year Warranty",
    specifications: {
      Connectivity: "Wi-Fi, Bluetooth",
      Assistant: "Alexa",
    },
    soldCount: 20000,
    returnPolicy: "30-day return",
    createdAt: formattedDate,
  },
];
